import os 

os.chdir('/Users/lucy/Desktop/summer/SummaryDataFile')

os.mkdir('OfficeMax')

os.mkdir('Pharmacia')
os.mkdir('Owens-Illinois')
os.mkdir('AMAX')
os.mkdir('Times Mirror')
os.mkdir('Sun Microsystems')
os.mkdir('Masco')
os.mkdir('Grumman')
os.mkdir('Ryerson Tull')
os.mkdir('Gannett')
os.mkdir('Pitney Bowes')
os.mkdir('Farmland Industries')
os.mkdir('FINA')
os.mkdir('Kerr-McGee')
os.mkdir('AMP')
os.mkdir('Agway')
os.mkdir('Air Products & Chem.')
os.mkdir('Hershey Foods')
os.mkdir('Varity')
os.mkdir('Rohm & Haas')
os.mkdir('Tyco International')
os.mkdir('Union Camp')
os.mkdir('Harris')
os.mkdir('Maytag')
os.mkdir('Berkshire Hathaway')
os.mkdir('Smurfit-Stone Container')
os.mkdir('Universal')
os.mkdir('Ethyl')
os.mkdir('Premark International')
os.mkdir('Teledyne')
os.mkdir('Seagate Technology')
os.mkdir('Loral')
os.mkdir('Hercules')
os.mkdir('Owens Corning')
os.mkdir('Illinois Tool Works')
os.mkdir('Hormel Foods')
os.mkdir('PerkinElmer')
os.mkdir('Paccar')
os.mkdir('Sherwin-Williams')
os.mkdir('Pennzoil')
os.mkdir('Temple-Inland')
os.mkdir('Readers Digest Assn.')
os.mkdir('Mapco')
os.mkdir('Avery Dennison')
os.mkdir('Diamond Shamrock')
os.mkdir('Ultramar Diamond Shamrock')
os.mkdir('Phelps Dodge')
os.mkdir('Land OLakes')
os.mkdir('AMDAHL')
os.mkdir('Armstrong Holdings')
os.mkdir('Baker Hughes')
os.mkdir('Hasbro')
os.mkdir('Goodrich')
os.mkdir('Ball')
os.mkdir('Engelhard')
os.mkdir('Total Petroleum')
os.mkdir('Whitman')
os.mkdir('Olin')
os.mkdir('Parker Hannifin')
os.mkdir('National Steel')
os.mkdir('McDermott')
os.mkdir('Willamette Industries')
os.mkdir('Becton Dickinson')
os.mkdir('Westvaco')
os.mkdir('Knight-Ridder')
os.mkdir('Quantum Chemical')
os.mkdir('Dean Foods')
os.mkdir('Dover')
os.mkdir('Intl. Multifoods')
os.mkdir('Conner Peripherals')
os.mkdir('Premcor')
os.mkdir('Maxxam')
os.mkdir('Manville')
os.mkdir('Brunswick')
os.mkdir('Collins & Aikman')
os.mkdir('Stanley Works')
os.mkdir('Louisiana-Pacific')
os.mkdir('Polaroid')
os.mkdir('Tosco')
os.mkdir('Tribune')
os.mkdir('E-SYSTEMS')
os.mkdir('ARMCO')
os.mkdir('Burlington Industries Equity')
os.mkdir('Tandem Computers')
os.mkdir('McGraw-Hill')
os.mkdir('Springs Industries')
os.mkdir('Molson Coors Brewing')
os.mkdir('Dow Corning')
os.mkdir('York International')
os.mkdir('GenCorp')
os.mkdir('Asarco')
os.mkdir('Morton International')
os.mkdir('Wang Laboratories')
os.mkdir('Central Soya')
os.mkdir('Arvin Industries')
os.mkdir('Pet')
os.mkdir('Mattel')

os.mkdir('MID-AMERICA DAIRYMEN')
os.mkdir('Sequa')
os.mkdir('Fruit of the Loom')
os.mkdir('Sonoco Products')
os.mkdir('Dow Jones')
os.mkdir('Rubbermaid')
os.mkdir('Echlin')
os.mkdir('USG')
os.mkdir('CENEX')
os.mkdir('New York Times')
os.mkdir('Shaw Industries')
os.mkdir('Witco')
os.mkdir('National Semiconductor')
os.mkdir('Imcera Group')
os.mkdir('Bausch & Lomb')
os.mkdir('Clorox')
os.mkdir('Sundstrand')
os.mkdir('Aeroquip-Vickers')
os.mkdir('Murphy Oil')
os.mkdir('Metaldyne')
os.mkdir('Burlington Resources')
os.mkdir('Freeport-McMoran')
os.mkdir('Cyprus Amax Minerals')
os.mkdir('Timken')
os.mkdir('National Service Industries')
os.mkdir('Harsco')
os.mkdir('General Signal')
os.mkdir('Nucor')
os.mkdir('Duracell International')
os.mkdir('Fleetwood Enterprises')
os.mkdir('Storage Technology')
os.mkdir('Newell Rubbermaid')
os.mkdir('Crown Central')
os.mkdir('American Greetings')
os.mkdir('Cabot')
os.mkdir('Lubrizol')
os.mkdir('Reliance Electric')
os.mkdir('Deluxe')
os.mkdir('Advanced Micro Devices')
os.mkdir('Lafarge')
os.mkdir('WestPoint Stevens')
os.mkdir('Great Lakes Chemical')
os.mkdir('Bowater')
os.mkdir('Nacco Industries')
os.mkdir('McCormick')
os.mkdir('Furniture Brands Intl.')
os.mkdir('Washington Post')
os.mkdir('Federal Paper Board')
os.mkdir('Hillenbrand Industries')

os.mkdir('Del Monte Foods')
os.mkdir('Lear')
os.mkdir('Joy Global')
os.mkdir('Nalco Chemical')
os.mkdir('Coltec Industries')
os.mkdir('Walter Industries')
os.mkdir('M.A. Hanna')
os.mkdir('Potlatch')
os.mkdir('Thiokol')
os.mkdir('Oryx Energy')
os.mkdir('Gold Kist Holdings')
os.mkdir('Crane')
os.mkdir('Wm. Wrigley Jr.')
os.mkdir('Great American Mgmt. & Inv.')
os.mkdir('Tektronix')
os.mkdir('Raychem')
os.mkdir('Dresser-Rand')
os.mkdir('Gerber Products')
os.mkdir('Varian Associates')
os.mkdir('Tecumseh Products')
os.mkdir('Rohr')


